name: dc-prod-py36
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - astropy=4.0.1.post1=py37h8f50634_0
  - boost-cpp=1.72.0=h8e57a91_0
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - certifi=2020.4.5.2=py37hc8dfbb8_0
  - cffi=1.14.0=py37hd463f26_0
  - cryptography=2.9.2=py37hb09aad4_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - cyrus-sasl=2.1.27=h063b49f_1
  - dqsegdb2=1.0.1=py_0
  - freetype=2.10.2=he06d7ca_0
  - gwdatafind=1.0.4=pyh9f0ad1d_1
  - gwosc=0.5.3=py_0
  - gwpy=1.0.1=py37_1
  - h5py=2.9.0=nompi_hf008753_1101
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - icu=64.2=he1b5a44_1
  - idna=2.9=py_1
  - intel-openmp=2020.1=217
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.2.0=py37h99015e2_0
  - krb5=1.17.1=h2fd8d38_0
  - ld_impl_linux-64=2.34=h53a641e_5
  - ldas-tools-al=2.6.4=hf7ed750_3
  - ldas-tools-framecpp=2.7.0=h9eccf00_3
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libedit=3.1.20191231=h46ee950_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - liblapack=3.8.0=16_openblas
  - libntlm=1.4=h516909a_1002
  - libopenblas=0.3.9=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=h2733197_1
  - ligo-common=1.0.4=py_0
  - ligo-segments=1.2.0=py37h516909a_2
  - ligotimegps=2.0.1=py_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he6710b0_0
  - matplotlib-base=3.2.2=py37h30547a4_0
  - mkl=2020.1=217
  - ncurses=6.1=hf484d3e_1002
  - nds2-client=0.16.5=hd02d5f2_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.5=py37h8960a57_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pillow=7.1.2=py37hb39fc2d_0
  - pip=20.1.1=py_1
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python-ldas-tools-al=2.6.7=py37h99015e2_2
  - python-ldas-tools-framecpp=2.6.9=py37h0da4684_1
  - python-nds2-client=0.16.7=py37h0da4684_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.0.0=py3.7_cuda9.0.176_cudnn7.4.1_1
  - readline=8.0=hf8c457e_0
  - scipy=1.4.1=py37ha3d9a3c_3
  - setuptools=47.3.1=py37hc8dfbb8_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.2.2=py_3
  - tornado=6.0.4=py37h8f50634_1
  - tqdm=4.46.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - xz=5.2.5=h516909a_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - click==7.1.2
    - dill==0.3.2
    - multiprocess==0.70.10
    - pycondor==0.5.0
    - torchsummary==1.5.1
prefix: /home/tri.nguyen/anaconda3/envs/dc-prod-py36

